//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHDCD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class BANGBAUHDQT
    {
        public BANGBAUHDQT()
        {
            this.SLPHIEUBAU = 0;
            this.CT_BAUHDQT = new HashSet<CT_BAUHDQT>();
        }
        [DisplayName("Mã đại hội")]
        public string MADH { get; set; }
         [DisplayName("Mã cổ đông")]
        public int MACD { get; set; }
         [DisplayName("Hình thức bầu")]
        public string HINHTHUCBAU { get; set; }
         [DisplayName("Số lượng phiếu bầu")]
        public Nullable<int> SLPHIEUBAU { get; set; }
    
        public virtual CT_DHCD CT_DHCD { get; set; }
        public virtual ICollection<CT_BAUHDQT> CT_BAUHDQT { get; set; }
    }
}
