//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHDCD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class BANGYKIEN
    {
        public BANGYKIEN()
        {
            this.SLDONGY = 0;
            this.SLKHONGDONGY = 0;
            this.SLYKKHAC = 0;
            this.CTBQYKIENs = new HashSet<CTBQYKIEN>();
        }
        [DisplayName("Mã ý kiến")]
        public int MAYK { get; set; }
        [DisplayName("Mã đại hội")]
        public string MADH { get; set; }
        [DisplayName("Nội dung ý kiến")]
        public string NOIDUNG { get; set; }
        [DisplayName("Số lượng phiếu đồng ý")]
        public Nullable<int> SLDONGY { get; set; }
        [DisplayName("Số lượng phiếu không đồng ý")]
        public Nullable<int> SLKHONGDONGY { get; set; }
        [DisplayName("Số lượng phiếu ý kiến khác")]
        public Nullable<int> SLYKKHAC { get; set; }
    
        public virtual DHCD DHCD { get; set; }
        public virtual ICollection<CTBQYKIEN> CTBQYKIENs { get; set; }
    }
}
