//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHDCD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class CT_BAUBKS
    {
        public CT_BAUBKS()
        {
            this.SLPHIEUBAU = 0;
            this.THOIGIANBAU = DateTime.Now;
        }
        [DisplayName("Mã bầu cử")]
        public int MACT { get; set; }
        public string MADH { get; set; }
        public Nullable<int> MANGDUOCBAU { get; set; }
        public Nullable<int> MANGDIBAU { get; set; }
        [DisplayName("Số lượng phiếu bầu")]
        public Nullable<int> SLPHIEUBAU { get; set; }
        [DisplayName("Hình thức bầu")]
        public string HINHTHUCBAU { get; set; }
        [DisplayName("Thời gian bầu")]
        public Nullable<System.DateTime> THOIGIANBAU { get; set; }
    
        public virtual BANGBAUBK BANGBAUBK { get; set; }
        public virtual CT_DHCD CT_DHCD { get; set; }
    }
}
