//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHDCD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class CT_DHCD
    {
        public CT_DHCD()
        {
            this.SLCP = 0;
            this.SLDAUQ = 0;
            this.HTDK = "Trực tiếp";
            this.SLCPSAUCUNG = 0;
            this.QUYENBAUCU = 0;
            this.CT_BAUBKS = new HashSet<CT_BAUBKS>();
            this.CT_BAUHDQT = new HashSet<CT_BAUHDQT>();
            this.UYQUYENs = new HashSet<UYQUYEN>();
            this.UYQUYENs1 = new HashSet<UYQUYEN>();
            this.CTBQYKIENs = new HashSet<CTBQYKIEN>();
        }

        [DisplayName("Mã đại hội")]
        public string MADH { get; set; }
        [DisplayName("Mã cổ đông")]
        public int MACD { get; set; }
        [DisplayName("SL cổ phiếu gốc")]
        public Nullable<int> SLCP { get; set; }
        [DisplayName("SLCP đã ủy quyền")]
        public Nullable<int> SLDAUQ { get; set; }
        [DisplayName("SLCP được ủy quyền")]
        public Nullable<int> SLDCUQ { get; set; }
        [DisplayName("Hình thức đăng kí")]
        public string HTDK { get; set; }
        [DisplayName("SLCP có thể ủy quyền")]
        public Nullable<int> SLCPSAUCUNG { get; set; }
        [DisplayName("Quyền bầu cử")]
        public Nullable<int> QUYENBAUCU { get; set; }
    
        public virtual BANGBAUBK BANGBAUBK { get; set; }
        public virtual BANGBAUHDQT BANGBAUHDQT { get; set; }
        public virtual CODONG CODONG { get; set; }
        public virtual ICollection<CT_BAUBKS> CT_BAUBKS { get; set; }
        public virtual ICollection<CT_BAUHDQT> CT_BAUHDQT { get; set; }
        public virtual ICollection<UYQUYEN> UYQUYENs { get; set; }
        public virtual ICollection<UYQUYEN> UYQUYENs1 { get; set; }
        public virtual ICollection<CTBQYKIEN> CTBQYKIENs { get; set; }
        public virtual DHCD DHCD { get; set; }
    }
}
