//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHDCD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class DHCD
    {
        public DHCD()
        {
            this.nQKin = 0;
            this.nQBefore = 0;
            this.nDeCuHDQT = 0;
            this.nUngCuHDQT = 0;
            this.nDeCuBKS = 0;
            this.nUngCuBKS = 0;
            this.ACTIVE = 0;
            this.TONGSOPHIEU = 0;
            this.BANGYKIENs = new HashSet<BANGYKIEN>();
            this.CT_DHCD = new HashSet<CT_DHCD>();
            this.thoiGian = DateTime.Now;
        }
        [DisplayName("Mã đại hội")]
        public string MADH { get; set; }
        [DisplayName("Tên đại hội")]
        public string TenDH { get; set; }
        [DisplayName("SL câu BQ kín")]
        public Nullable<int> nQKin { get; set; }
        [DisplayName("SL câu BQ trước đại hội")]
        public Nullable<int> nQBefore { get; set; }
        [DisplayName("SL đề cử vào HĐQT")]
        public Nullable<int> nDeCuHDQT { get; set; }
        [DisplayName("SL ứng cử vào HĐQT")]
        public Nullable<int> nUngCuHDQT { get; set; }
        [DisplayName("SL đề cử vào BKS")]
        public Nullable<int> nDeCuBKS { get; set; }
        [DisplayName("SL ứng cử vào BKS")]
        public Nullable<int> nUngCuBKS { get; set; }
        [DisplayName("Thời gian diễn ra")]
        public Nullable<System.DateTime> thoiGian { get; set; }
        [DisplayName("Active")]
        public Nullable<int> ACTIVE { get; set; }
        [DisplayName("Tổng số phiếu")]
        public Nullable<int> TONGSOPHIEU { get; set; }
    
        public virtual ICollection<BANGYKIEN> BANGYKIENs { get; set; }
        public virtual ICollection<CT_DHCD> CT_DHCD { get; set; }
    }
}
