//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHDCD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class UYQUYEN
    {
        public UYQUYEN()
        {
            this.SLUQ = 0;
            this.THOIGIAN = DateTime.Now;
        }

        [DisplayName("Mã ủy quyền")]
        public int MAUQ { get; set; }
        [DisplayName("Mã đại hội")]
        public string MADH { get; set; }
        [DisplayName("Mã người chuyển")]
        public int MANGCHUYEN { get; set; }
        [DisplayName("Mã người nhận")]
        public int MANGNHAN { get; set; }
        [DisplayName("SLCP ủy quyền")]
        public Nullable<int> SLUQ { get; set; }
        [DisplayName("Thời gian ủy quyền")]
        public Nullable<System.DateTime> THOIGIAN { get; set; }
    
        public virtual CT_DHCD NGUOICHUYEN { get; set; }
        public virtual CT_DHCD NGUOINHAN { get; set; }
    }
}
